Repository biojava/biojava, pull requests merged in 2018-08, with the labels that each got.

#786 Solved #712: Bonds are now also copied by clone()
  biojava-alignment/src/test/java/org/biojava/nbio/alignment/TestSubOptimalMSA.java
  biojava-alignment/src/test/java/org/biojava/nbio/phylo/TestForesterWrapper.java
  biojava-structure/src/main/java/org/biojava/nbio/structure/AminoAcidImpl.java
  biojava-structure/src/main/java/org/biojava/nbio/structure/HetatomImpl.java
  biojava-structure/src/main/java/org/biojava/nbio/structure/NucleotideImpl.java
  biojava-structure/src/test/java/org/biojava/nbio/structure/TestCloning.java
Labels: enhancement

#785 Update Jmol version and revert to MMCIF format for JmolPanel
  biojava-structure-gui/pom.xml
  biojava-structure-gui/src/main/java/org/biojava/nbio/structure/align/gui/jmol/JmolPanel.java
Labels: bug

#788 Extending back the changelog
  CHANGELOG.md
Labels: documentation
