Repository biojava/biojava, pull requests merged in 2018-03, with the labels that each got.

#737 Refactoring and docs as per #592
  biojava-structure/src/main/java/org/biojava/nbio/structure/align/StructurePairAligner.java
  biojava-structure/src/main/java/org/biojava/nbio/structure/align/helper/AlignUtils.java
  biojava-structure/src/main/java/org/biojava/nbio/structure/align/multiple/MultipleAlignmentEnsembleImpl.java
  biojava-structure/src/main/java/org/biojava/nbio/structure/align/pairwise/FragmentJoiner.java
  biojava-structure/src/main/java/org/biojava/nbio/structure/symmetry/utils/SymmetryTools.java
Labels: documentation, minor

#743 Reset the QCP 2-step calculation
  biojava-structure/src/main/java/org/biojava/nbio/structure/geometry/SuperPositionQCP.java
  biojava-structure/src/test/java/org/biojava/nbio/structure/geometry/TestSuperPosition.java
  biojava-structure/src/test/java/org/biojava/nbio/structure/geometry/TestSuperPositionQCP.java
Labels: enhancement

#746 Fixing the sifts test to not use external resources
  biojava-structure/src/main/java/org/biojava/nbio/structure/io/sifts/SiftsChainToUniprotMapping.java
  biojava-structure/src/test/java/org/biojava/nbio/structure/io/sifts/SiftsChainToUniprotMappingTest.java
  biojava-structure/src/test/resources/org/biojava/nbio/structure/io/sifts/mock_sifts.tsv
Labels: testing

#747 Standard LGPL license as provided by github template
  HEADER.txt
  LICENSE
  development/addlicense.sh
Labels: documentation

#748 Maven plugin upgrade
  biojava-integrationtest/src/test/java/org/biojava/nbio/structure/test/ecod/EcodInstallationTest.java
  biojava-integrationtest/src/test/java/org/biojava/nbio/structure/test/io/TestAtomCachePerformance.java
  biojava-integrationtest/src/test/java/org/biojava/nbio/structure/test/io/TestLongPdbVsMmCifParsing.java
  biojava-integrationtest/src/test/java/org/biojava/nbio/structure/test/symmetry/TestQuatSymmetryDetectorExamples.java
  biojava-structure/src/main/java/org/biojava/nbio/structure/align/util/AtomCache.java
  biojava-structure/src/main/java/org/biojava/nbio/structure/io/BondMaker.java
  biojava-structure/src/test/java/org/biojava/nbio/structure/TestBond.java
  biojava-structure/src/test/java/org/biojava/nbio/structure/TestDownloadChemCompProvider.java
  biojava-structure/src/test/java/org/biojava/nbio/structure/asa/TestAsaCalc.java
  pom.xml
Labels: organization

#749 Removed v4 deprecations
  biojava-alignment/src/main/java/org/biojava/nbio/alignment/io/StockholmStructure.java
  biojava-core/src/main/java/org/biojava/nbio/core/sequence/compound/NucleotideCompound.java
  biojava-core/src/main/java/org/biojava/nbio/core/sequence/transcription/RNAToAminoAcidTranslator.java
  biojava-genome/src/main/java/org/biojava/nbio/genome/parsers/gff/Feature.java
  biojava-genome/src/main/java/org/biojava/nbio/genome/parsers/gff/FeatureList.java
  biojava-genome/src/main/java/org/biojava/nbio/genome/parsers/gff/Location.java
  biojava-integrationtest/src/test/java/org/biojava/nbio/structure/test/StructureToolsTest.java
  biojava-modfinder/src/main/java/org/biojava/nbio/protmod/structure/ModifiedCompoundImpl.java
  biojava-structure-gui/src/main/java/org/biojava/nbio/structure/align/gui/DisplayAFP.java
  biojava-structure-gui/src/main/java/org/biojava/nbio/structure/gui/JMatrixPanel.java
  biojava-structure-gui/src/main/java/org/biojava/nbio/structure/gui/RasmolCommandListener.java
  biojava-structure/src/main/java/org/biojava/nbio/structure/Identifier.java
  biojava-structure/src/main/java/org/biojava/nbio/structure/PDBCrystallographicInfo.java
  biojava-structure/src/main/java/org/biojava/nbio/structure/StructureTools.java
  biojava-structure/src/main/java/org/biojava/nbio/structure/align/StructurePairAligner.java
  biojava-structure/src/main/java/org/biojava/nbio/structure/align/ce/CECalculator.java
  biojava-structure/src/main/java/org/biojava/nbio/structure/align/ce/StartupParameters.java
  biojava-structure/src/main/java/org/biojava/nbio/structure/align/client/StructureName.java
  biojava-structure/src/main/java/org/biojava/nbio/structure/align/model/AFPChain.java
  biojava-structure/src/main/java/org/biojava/nbio/structure/align/util/AtomCache.java
  biojava-structure/src/main/java/org/biojava/nbio/structure/align/util/CacheFactory.java
  biojava-structure/src/main/java/org/biojava/nbio/structure/align/util/RotationAxis.java
  biojava-structure/src/main/java/org/biojava/nbio/structure/align/util/UserConfiguration.java
  biojava-structure/src/main/java/org/biojava/nbio/structure/cath/CathDomain.java
  biojava-structure/src/main/java/org/biojava/nbio/structure/io/CAConverter.java
  biojava-structure/src/main/java/org/biojava/nbio/structure/io/FileParsingParameters.java
  biojava-structure/src/main/java/org/biojava/nbio/structure/io/LocalPDBDirectory.java
  biojava-structure/src/main/java/org/biojava/nbio/structure/io/PDBFileReader.java
  biojava-structure/src/main/java/org/biojava/nbio/structure/io/StructureProvider.java
  biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmcif/MMCIFFileTools.java
  biojava-structure/src/main/java/org/biojava/nbio/structure/quaternary/BioAssemblyTools.java
  biojava-structure/src/main/java/org/biojava/nbio/structure/scop/ScopInstallation.java
  biojava-structure/src/main/java/org/biojava/nbio/structure/symmetry/internal/SymmetryAxes.java
  biojava-structure/src/main/java/org/biojava/nbio/structure/symmetry/utils/SymmetryTools.java
  biojava-structure/src/test/java/org/biojava/nbio/structure/symmetry/internal/TestSymmetryAxes.java
Labels: organization

#757 A changelog draft for the 5.0.0 release
  CHANGELOG.md
Labels: documentation
